export const fakeLightTopo = {
  altitude: '775.00',
  approachDescription: "Depuis le parking, prendre le sentier qui monte dans la continuité de la route. Après 12-15min de marche, vous arriverez à une esplanade d'herbe surmontant une petite falaise (où il est possible de faire de l'initiation). Un panneau indique le site d'escalade à l'entrée de l'esplanade.\nDepuis l'esplanade, prendre le sentier qui part derrière le panneau pour monter vers les premiers blocs.",
  approachDifficultyLabel: 'Moyen',
  approachTime: 15,
  cleaningDate: null,
  closestCity: 'Yzéron',
  creator: 'Flavien C',
  dangerDescription: 'Il y a beaucoup de pentes',
  description: 'Le site d’Yzéron est situé sur le massif de Py froid à environ 800m d’altitude. Il est le plus grand site de bloc de la région Lyonnaise avec une grande diversité de profil (dévers, dalle, réta...). L’esplanade sépare la plus grande partie du site en amont, et une falaise idéale pour l’initiation, située en contrebas. La forêt protège une bonne partie du site contre les aléas météorologiques ce qui, combiné à l’altitude, permet la pratique de la grimpe toute l’année.',
  difficulties: [
    '4+',
    '6a',
    '6b',
    '5b',
    '4+',
    '3+',
    '7a',
    '7b',
    '6a',
    '3+',
    '6b',
    '6a+',
    '5c',
    '4+',
    '6b',
    '6c',
    '6c+',
    '6a+',
    '6b',
    '6a+',
    '5a',
    '4+',
    '5c',
    '6c+',
    '6a+',
    '4',
    '4+',
    '5a',
    '5b',
    '6a',
    '4+',
    '5b',
    '6a+',
    '6a',
    '4+',
    '4',
    '3+',
    '3',
    '5c',
    '6a',
    '3',
    '3',
    '6c',
    '6b',
    '5a+',
    '5c+',
    '5a+',
    '6c',
    '6a+',
    '6a+',
    '5a+',
    '5c',
    '6b',
    '6a',
    '7a',
    '4+',
    '6a',
    '5b+',
    '6c',
    '5b',
    '4',
    '6c',
    '6a+',
    '6a',
    '4',
    '5a+',
    '5a',
    '4+',
    '6b+',
    '7a+',
    '7a',
    '5b',
    '6c',
    '6a',
    '6b',
    '5b+',
    '6b',
    '5c+',
    '3',
    '3+',
    '6a+',
    '3',
    '4',
    '4',
    '6b',
    '6c',
    '6a+',
    '4+',
    '3',
    '3',
    '6b',
    '3+',
    '6a',
    '4+',
    '4',
    '6a',
    '5c',
    '5b+',
    '6a',
    '5c',
    '3',
    '6a+',
    '3',
    '7a',
    '7a+',
    '6a+',
    '6b',
    '7b',
    '7b',
    '5c',
    '6a',
    '4',
    '3+',
    '3',
    '5a',
    '6b',
    '5a+',
    '5c',
    '6a',
    '6c',
    '3+',
    '3+',
    '4+',
    '5a',
    '7a',
    '4',
    '3+',
    '4+',
    '4',
    '5b+',
    '6c',
    '5c',
    '6c',
    '6a',
    '6b+',
    '6a',
    '7b',
    '7b',
    '5a',
    '6c',
    '6c',
    '5c',
    '6a',
    '4',
    '5a',
    '5a+',
    '6b',
    '7a',
    '6b',
    '5b',
    '5c',
    '5b',
    '6b+',
    '6b',
    '7c',
    '6c',
    '6b',
    '6b',
    '5b',
    '5c',
  ],
  forbiddenReason: null,
  gears: [],
  hasBins: false,
  hasDanger: true,
  hasOtherGears: false,
  hasPicnicArea: false,
  hasShelter: false,
  hasToilets: false,
  hasWaterSpot: false,
  id: 2,
  isAdaptedToChildren: true,
  isForbiddenSite: false,
  location: { lat: '45.701356', lng: '4.607264' },
  mainImage:
    {
      id: 16,
      url: '/public/uploads/boulder/image/5b558375709fbbacae9e5dcb746c8e10e7fa083f.jpeg',
    },
  name: 'Les roches qui dansent beaucoup souvent',
  numberOfBoulder: 67,
  numberOfTrack: 162,
  otherGears: null,
  otherRemarks: null,
  rockTypeLabel: 'Gneiss',
  securityInstructions: null,
  status: 'submitted',
  type: null,
  updatedAt: '21-11-06',
  validatedAt: '06-11-21',
  submittedAt: '06-11-21',
};
